; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
    #Include bits.ahk
;#Include %A_ScriptDir%\lib\Neutron.ahk
global LogGames := A_AppDataCommon "\geo3d\gameslist.txt" 
LogRead()

browsefor()
    
browsefor()
{
    global selectgame, Gameexe, Gamepath, Gameextenstion, Gamenameonly, successbi
    ;declare to be used elsewhere
    
    FileSelectFile, Selectgame, 1, , Select a game, Application (*.exe)
    ;browse for file
    if (Selectgame = "")
    {
        MsgBox, You didn't select anything.
        goto, leaver
    }
    else
    {
        SplitPath, Selectgame, Gameexe, Gamepath, Gameextenstion, Gamenameonly
    }
    bat := Gamepath "\1.bat"
    sigcheck := A_ScriptDir "\sigcheck.exe"
    logger := A_ScriptDir "\output.txt"
    
    filecopy, %sigcheck%, %Gamepath%
    sigcheck := Gamepath "\sigcheck.exe"
    writetobat = 
    (
    sigcheck.exe -a -c %Gameexe% > %logger% 
    
    )
    FileDelete, %bat%
    FileDelete, %logger%
    FileAppend, %writetobat%, %bat%
    ;check for 64x or 32x
    Run, %bat%, %GamePath%, min
    sleep, 500
    Loop, read, %logger%
    {
        if (A_Index="2")
        { 
            Col := A_LoopReadLine
            Field := StrSplit(Col, ",") 
            bit := Field[12]
            Delim := `""""
            
            bit := StrReplace(bit, Delim)
            ; NewStr := StrReplace(Str, """")
            
            ; bit := Trim(bit) """
            Msgbox % bit ; <<<<<<< the field 1 and row 1
            if InStr(bit,"32")
            {
                bits := "32"
                install(bits)
            }
            else if InStr(bit,"64")
            {
                bits := "64"
                install(bits)                
            }
            else
                msgbox, unknown game version                       
        }
    }
    
    leaver:
    }
    /*

    next function

        */

    LogRead()
    {
        global LogGames
        sep := "`n"
        GameLocation:=[]
        countlines:=[]
        GameExe:=[] 
        Loop, Read, %LogGames%
        {
            Info := A_LoopReadLine
            GameInfo := StrSplit(Info, ",") 
            GameLocation[A_Index] := GameInfo[1]
            GameExe[A_Index] := GameInfo[2]
            countlines := A_Index 
        } 
        
        Loop % countlines
        {
            GL := GameLocation[A_Index]
            GE := GameExe[A_Index] 
            html=
(
%html%
<tr>
<td align="center">
<a class="btn btn-default"><em class="fa fa-pencil"></em></a>
<a class="btn btn-danger"><em class="fa fa-trash"></em></a>
</td>
<td class="hidden-xs">1</td>
)
            html := html . "<td>" . GE . "</td>" . sep
            . "<td>" . GL . "</td>" . sep
            . "</tr>"
            Msgbox, %html% 
        }
    }