; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
Geo3D := "Geo3D" 
  
; >>> resolve geo3d location
loop, Files, %A_ScriptDir%\*.zip, R
{
    if InStr(A_LoopFileName, Geo3D)
    {
       msgbox, file path is %A_LoopFileFullPath%
    } 
}
 