
  ; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
#Include bits.ahk 
;#Include %A_ScriptDir%\lib\Neutron.ahk
global LogGames := A_AppDataCommon "\geo3d\gameslist.txt" 
global Dir := A_AppDataCommon "\geo3d"
gamepath := A_AppDataCommon "\geo3d\gameslist\"
LocalGeo3D := A_ScriptDir "\geo3d\32-bit"
bat5 := A_ScriptDir "\5.bat"
bat55=
(
xcopy "%LocalGeo3D%" "%gamepath%" /C /O /I /H /y"
)  
FileAppend, %bat55%, %bat5% 
sleep, 100000