; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
 

install(bits)
{
    global selectgame, gamepath, successbi
    VREx := "VRExport_" bits ".addon"
    filesafe := [VREx, "ReShade.ini", "Geo3D.addon", "dxgi.dll", "3DToElse.fx"] 
    Geo3D := "Geo3D"
    
    ;check for 64x or 32x
    sleep, 200
    counterx := 1  
     
    ; >>> resolve files in game dir and check for dupes
    for index, value in filesafe
    {
        loop, files, gamepath
        {
            if InStr(A_LoopFileFullPath, value)
            {
                backup[counterx] := A_LoopFileFullPath
                counterx++
            }
        }
    }
    backupfolder := gamepath "\backup_files_geo_vr"
    FileCreateDir, %backupfolder% 
    for index, value in backup
    {
        LoopFileBackup := backup[index]
        FileCopy, %LoopFileBackup%, %backupfolder%, 1 
    }
    
    ;Run, %7zbat%, %A_ScriptDir%, min
 
    LocalGeo3D := A_ScriptDir "\geo3d\" bits "-bit"
    bat5 := A_ScriptDir "\5.bat"
    bat=
(
xcopy "%LocalGeo3D%" "%gamepath%" /C /O /I /H /y"
) 
    filedelete, %bat5% 
    FileAppend, %bat%, %bat5% 
    sleep, 100
    Run, %bat%
    for index, value in filesafe
    {
        Geo3DFiles := A_ScriptDir "\geo3d\" bits "-bit\" value
        filecopy, %Geo3DFiles%, %gamepath%, 1
    }
    
    successbi := "1"
    leaver2:
}


    /*
 
    */

    

LogRead()
{
    global LogGames, html, neutron
    if !FileExist(LogGames)
    {  
        texter=
(
,D:\SampleGame\Battlefield 1\bf1.exe,bf1.exe,bf1,

)
        FileAppend, %texter%, %LogGames%
        goto, Leaver3
    }
    html:=""
    sep := "`n"
    GameLocation:=[]
    countlines:=[]
    GameExe:=[] 
    Loop, Read, %LogGames%
    {
        if (A_LoopReadLine != "") {
            Info := A_LoopReadLine
            GameInfo := StrSplit(Info, ",") 
            GameLocation[A_Index] := GameInfo[2]
            GameExe[A_Index] := GameInfo[3]
            countlines := A_Index 
        } 
    }

    ; ADD HTML TO GAME LIST
    Loop %countlines%
    {
        GL := GameLocation[A_Index]
        GE := GameExe[A_Index] 
        if (GE != "" or GL != "")
        {
        html=
(
%html%
<tr>
<td align="center"> 
<a class="btn btn-danger" onclick="ahk.Uninstall(event)" id="%GE%"><em class="fa fa-trash"></em></a>
</td>
<td class="hidden-xs">%A_Index%</td>
)
        html := html . "<td>" . GE . "</td>" . sep
        . "<td>" . GL . "</td>" . sep
        . "</tr>" 
    }
    }
    neutron.qs("#tabler").innerHTML := ""
    neutron.qs("#tabler").innerHTML:=html
    Leaver3:
} 
    /*
 
    */ 
AddtoLog(bits) 
{
    global loggame, selectgame, gamepath, gameexe 
    FileAppend, 
(

,%selectgame%,%gameexe%,%gamepath%,%bits%,
), %loggames%

}

Removefromlog(countlines) 
{
    global loggames, selectgame, gamepath, gameexe 
    Loop, Read, %LogGames%, out.txt
    {
        if (A_Index=countlines)
        { 
            continue
        }
        else 
            FileAppend %A_LoopReadLine%`n
    }
    FileMove, out.txt, %LogGames%, 1

}
