; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
 

install(bits)
{
    global selectgame, gamepath, successbi
    VREx := "VRExport_" bits ".addon"
    filesafe := [VREx, "ReShade.ini", "Geo3D.addon", "dxgi.dll", "3DToElse.fx"]
    7zbat := A_ScriptDir "\geo11\2.bat"
    7zlog := A_ScriptDir "\output.txt"
    Geo3D := "Geo3D"
    write7zbat := "7za x " bits "-bit.7z -o" gamepath "\ -y -r"
    
    FileDelete, %7zbat%
    FileDelete, %7zlog%
    FileAppend, %write7zbat%, %7zbat%
    ;check for 64x or 32x
    sleep, 500
    counterx := 1 
    ; >>> resolve geo3d location
    loop, files,  A_ScriptDir
    {
        if InStr(A_LoopFileFullPath, Geo3D)
        {
           msgbox, file path is %A_LoopFileFullPath%
        }
    }
    ; >>> resolve files in game dir and check for dupes
    for index, value in filesafe
    {
        loop, files,  gamepath
        {
            if InStr(A_LoopFileFullPath, value)
            {
                backup[counterx] := A_LoopFileFullPath
                counterx++
            }
        }
    }
    backupfolder := gamepath "\backup_files_geo_vr"
    FileCreateDir, %backupfolder% 
    for index, value in backup
    {
        LoopFileBackup := backup[index]
        FileCopy, %LoopFileBackup%, %backupfolder%, 1 
    }
    
    Run, %7zbat%, %A_ScriptDir%, min

    /*
    for index, value in filesafe
    {
        filecopy, filesafe[index], gamepath, 1
    }
    FileCreateDir,\
    */
    successbi := "1"
    leaver2:
}


    /*
 
    */



LogRead()
{
    global LogGames, html, neutron
    if !FileExist(LogGames)
    {  
        texter=
(
,D:\SampleGame\Battlefield 1\bf1.exe,bf1.exe,bf1,

)
        FileAppend, %texter%, %LogGames%
        goto, Leaver3
    }
    sep := "`n"
    GameLocation:=[]
    countlines:=[]
    GameExe:=[] 
    Loop, Read, %LogGames%
    {
        Info := A_LoopReadLine
        GameInfo := StrSplit(Info, ",") 
        GameLocation[A_Index] := GameInfo[2]
        GameExe[A_Index] := GameInfo[3]
        countlines := A_Index 
    } 
    
    Loop %countlines%
    {
        GL := GameLocation[A_Index]
        GE := GameExe[A_Index] 
        html=
(
%html%
<tr>
<td align="center"> 
<a class="btn btn-danger"><em class="fa fa-trash"></em></a>
</td>
<td class="hidden-xs">%A_Index%</td>
)
        html := html . "<td>" . GE . "</td>" . sep
        . "<td>" . GL . "</td>" . sep
        . "</tr>"
        Msgbox, %html% 
    }
    
    neutron.qs("#tabler").innerHTML:=html
    Leaver3:
}



    /*
 
    */

AddtoLog() 
{
    global loggame, selectgame, gamepath, gameexe, bits
    FileAppend, 
(

,%selectgame%,%gameexe%,%gamepath%,%bit%,
), %loggames%

}

Removefromlog() 
{
    global loggame, selectgame, gamepath, gameexe 
    Loop, Read, %LogGames%, out.txt
    {
        if InStr(A_LoopReadLine, gameexe)
        { 
            continue
        }
        else 
            FileAppend %A_LoopReadLine%`n
    }
    FileMove, out.txt, %LogGames%, 1

}
