; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1  
Title := "Please Confirm?", Sec := 5

SetTimer, Countdown, 1000

MsgBox, 64, %Title%, Will launch in %Sec% seconds, %Sec%

Return



Countdown:

 ControlSetText, Static2, % "Will launch in " (Sec:=Sec-1) " seconds"

               , %Title% ahk_class #32770

Return
