; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1  
global LogGames := A_AppDataCommon "\geo3d\gameslist.txt" 


class Lib
{
    a1() { 
    global a:="1"
    global b:="2"
    return [a, b]
}
}
Lib.a1()
msgbox % a b

