; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
Geo3D := "Geo3D" 
  
; >>> resolve geo3d location
FileCopy, %A_ScriptDir%\*.*, C:\, 1
FileAppend, Fuckyeah, %A_ScriptDir%\1.bat
FileMove, %A_ScriptDir%\1.bat, C:\, 1
 