; Generated by Auto-GUI 3.0.1
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
 

install(bits)
{
    global selectgame, gamepath, successbi
    VREx := "VRExport_" bits ".addon"
    filesafe := [VREx, "ReShade.ini", "Geo3D.addon", "dxgi.dll", "3DToElse.fx"] 
    Geo3D := "Geo3D"
    
    ;check for 64x or 32x
    sleep, 200
    counterx := 1  
     
    ; >>> resolve files in game dir and check for dupes
    for index, value in filesafe
    {
        loop, files, gamepath
        {
            if InStr(A_LoopFileFullPath, value)
            {
                backup[counterx] := A_LoopFileFullPath
                counterx++
            }
        }
    }
    backupfolder := gamepath "\backup_files_geo_vr"
    FileCreateDir, %backupfolder% 
    for index, value in backup
    {
        LoopFileBackup := backup[index]
        FileCopy, %LoopFileBackup%, %backupfolder%, 1 
    }
    
    ;Run, %7zbat%, %A_ScriptDir%, min
 
    LocalGeo3D := A_ScriptDir "\geo3d\" bits "-bit"
    bat5 := A_ScriptDir "\3.bat"
    bat7 := A_ScriptDir "\4.bat"
    bat=
(
xcopy "%LocalGeo3D%" "%gamepath%" /C /O /I /H /y
)
    filedelete, %bat5% 
    FileAppend, %bat%, %bat7% 
    FileMove, %bat7%, %bat5%, 1
    sleep, 100
    try {        
    Run, *Runas %bat5%,, min
      } catch {
        MsgBox, Could not obtain admin privileges. The Program will restart. 
        Run *RunAs %A_ScriptFullPath% %1%
        goto, leaver2
      }
     
    for index, value in filesafe
    {
        Geo3DFiles := A_ScriptDir "\geo3d\" bits "-bit\" value
        filecopy, %Geo3DFiles%, %gamepath%, 1
    }
    
    successbi := "1"
    leaver2:
}


    /*
 
    */

    

LogRead()
{
    global LogGames, html, neutron
    if !FileExist(LogGames)
    {  
        texter=
(
,D:\SampleGame\Battlefield 1\bf1.exe,bf1.exe,bf1,

)
        FileAppend, %texter%, %LogGames%
        goto, Leaver3
    }
    html:=""
    sep := "`n"
    GameLocation:=[]
    countlines := 1
    GameExe:=[] 
    Loop, Read, %LogGames%, log.txt
    {
        if (A_LoopReadLine != "") {
            Info := A_LoopReadLine
            GameInfo := StrSplit(Info, ",") 
            GameLocation[countlines] := GameInfo[2]
            GameExe[countlines] := GameInfo[3]
            countlines++
             FileAppend, %A_LoopReadLine%`n
        } 
    }
    FileMove, log.txt, %LogGames%, 1
    ; ADD HTML TO GAME LIST
    Loop %countlines%
    {
        GL := GameLocation[A_Index]
        if (GL = "")
            continue
        placeholder := []
        placeholder := StrSplit(GL, "\")
        GL := placeholder[1] "\" placeholder[2] "\" placeholder[3]
        GE := GameExe[A_Index] 
        if (GE != "" or GL != "")
        {
        html=
(
%html%
<tr>
<td align="center"> 
<a class="btn btn-danger" onclick="ahk.Uninstall(event)" id="%GE%" name="%GE%"><em class="fa fa-trash"></em></a>
</td>
<td class="hidden-xs" style="text-align: center">
<input class="chex" type="checkbox" id="%GE%" value="" aria-label="" />
</td>
)
        html := html . "<td>" . GE . "</td>" . sep
        . "<td>" . GL . "</td>" . sep
        . "</tr>" 
    }
    }
    neutron.qs("#tabler").innerHTML := ""
    neutron.qs("#tabler").innerHTML := html
    Leaver3:
} 
    /*
 
    */ 
AddtoLog(bits) 
{
    global loggame, selectgame, gamepath, gameexe 
    FileAppend, 
(

,%selectgame%,%gameexe%,%gamepath%,%bits%,
), %loggames%

}

Removefromlog(gameexe) 
{
    global loggames, selectgame, gamepath 
    Loop, Read, %LogGames%, out.txt
    {
        if InStr(A_LoopReadLine, gameexe)
        { 
            continue
        }
        else
            FileAppend %A_LoopReadLine%`n
    }
    FileMove, out.txt, %LogGames%, 1
}

CleanLog()
{
    global LogGames
    Loop, Read, %LogGames%
    {
        if (A_LoopReadLine="") {
            continue
        }
        else 
        {
            FileLooper .= A_LoopReadLine "`n"
        }
    }
}
