; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1
WMI := "WmiData.csv"
CSV := []
countx = 1
Delim := `"""" 
Loop, Read, %Wmi%
{
	if InStr(A_LoopReadLine, "Steam")
	{
		CSV := StrSplit(A_LoopReadLine, ",")
		A1 := CSV[3]
		Games[countx] := StrReplace(A1, Delim) 
		countx++
	}
}
