; Generated by Auto-GUI 3.0.1
#NoEnv 
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1 
#SingleInstance, Force
 
global LogGames := A_AppDataCommon "\geo3d\gameslist.txt" 
 ;OT.ReadLog()
; msgbox % GameExe[1]


class OT
{
 ReadLog() {
        global
        GameExe:=[]
        GameLocation:=[]
        bits:=[]
        countlines:=1
        Loop, Read, %LogGames%
        {
            if (A_LoopReadLine != "") {
                Info := A_LoopReadLine
                GameInfo := StrSplit(Info, ",") 
                GameLocation[countlines] := GameInfo[4]
                GameExe[countlines] := GameInfo[3]
                bits[countlines] := GameInfo[5]
                countlines++
            } 
        } 
        } 
    }


 /*
Class OT
{
    ReadLog() {
    global
    countlines:=1  
 
            GameExe := ["a","b"]
    }  
    }  