; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir, %A_ScriptDir%
SetBatchLines -1
#include epron.ahk

Gui,+AlwaysOnTop
Gui Add, Link, x26 y270 w137 h21, <a href="https://github.com/samfisherirl/heresphere-auto-stream">ReadMe</a>

Gui Add, Button, vBtnGobabygo gGO x24 y16 w157 h230, GOBABYGO
Gui Add, Button, vRest gReset x192 y16 w157 h230, RESET

Gui Show, w360 h320, Window
Return

GO:
Doer()
Return

Reset:
Reload
return

GuiEscape:
GuiClose:
    ExitApp
